# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lintandcheck:
    runs-on: ubuntu-latest
    container: speedphoenix/gdscript-tools:latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Testing to see what the workspace looks like
        run: |
          cd /github/workspace/
          ls
          echo separator
          ls $GITHUB_WORKSPACE

      # Might need to change the directory depending on what should actuallly be used
      - name: check and lint
        run: |
          cd /github/workspace/
          gdlint scripts/*.gd
